### ISSUE TITLE
add literature references

### ISSUE THREAD

**Issue by Beliavsky** [VinceNeede/fortran_rng#1]
Could you add literature references in the Readme or the codes for the algorithms used by the random number generators?

**Comment by VinceNeede** [comment]
I have added some references and an example of the xoshiro256 usage, I hope it is enough

**Comment by Beliavsky** [comment]
That's good, thanks. I added your project to my directory of Fortran codes at https://github.com/Beliavsky/Fortran-code-on-GitHub
